import discord
from discord.ext import commands

class Copypastas(commands.Cog):

    '''
       Hello, user that is reading this!
       In this class, you will find every copypasta from our selfbot.
    '''

    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def masturbate(self, ctx):
        await ctx.message.delete()
        await ctx.channel.send("Please DO NOT announce to the server when you are going to masturbate. This has been a reoccurring issue, and I’m not sure why some people have such under developed social skills that they think that a server full of mostly male strangers would need to know that. No one is going to be impressed and give you a high five (especially considering where that hand has been). I don’t want to add this to the rules, since it would be embarrassing for new users to see that we have a problem with this, but it is going to be enforced as a rule from now on. If it occurs, you will be warned, then additional occurrences will be dealt with at the discretion of modstaff. Thanks.")
    @commands.command()
    async def discorddown(self, ctx):
        await ctx.message.delete()
        await ctx.channel.send("Discord's down. Fear not, kitten. Daddy shall return with nitro in clutch. The six month one, like promised. However, those at Discord headquarters... shall not be treated so mercifully. Anyone who severes my connection with kitten will experience a hell no devil can offer!\n\ni cant talk to my kitten.....grr....my...demon..arecoming out..iCANT HANDLE THIS..\n\n10 mins without discord.. i miss my kittens.. i dont know what to do.. i think im dying")
    @commands.command()
    async def havefunkiddo(self, ctx):
        await ctx.message.delete()
        await ctx.channel.send("Right now, I'm a click away from using an SQL injection attack to gain access to the database of this website and gain your login credentials, as well as your IP address. I'll then proceed to leak your IP address onto my hacker forums, and then using an IP locator, I'll easily find your house and your name. With that I can access your social media accounts and proceed to ruin your life. You think I'm bluffing? You think that just because a bunch of 7 year olds say they can 'hack', but actually can't, that I can't either? Let me shatter that facade for you. Using my team of hackers, we can trace what websites you've visited and what keystrokes you've used, and with that, I can get into your parents' bank account. I can drain it and make you dirt poor. Have you ever felt what it's like to be homeless? Well, you're about to. I can also use cross-site scripting to redirect your web browser to one of my private sites, and download illegal files onto your computer and get your parents locked up in prison. I'm your worst nightmare, and I'm about to make you endure living Hell. I'm nowhere and everywhere at the same time. Have fun regretting your existence, kiddo.")
    @commands.command()
    async def imjustgoingtosayit(self, ctx):
        await ctx.message.delete()
        await ctx.channel.send("You know what? I'm just going to say it. This server fucking sucks. I don't give a shit if the admins will mute me or if I get banned, but I want to get my message across, because it amazes me how many idiots in this server have a poor taste in quality. This server is like a fucking mental ward, and you all need to seek help. It's always the same damn shit everyday, and nothing new ever comes out of anyone's shriveled brains. Where are all the dank memes? Where are all of the good jokes? Where is all the dark humour? All I see is the same fucking Tumblr screenshots, and it's honestly boring as fuck. ALL of you are boring as fuck, if I'm being frank. I have pity for your parents, because I wouldn't question how would I able to nurture someone so milquetoast and ignorant for 18 years without putting a bullet through my head. You're all lame as fuck. I feel more stupider interacting with you all, and I wouldn't want to spend another second in this toxic atmosphere. Hell I'm actually glad this group exists. It keeps all the unfunny pricks away from the server that appreciate quality in their content. I hope you all get drafted and never come back. I'm done with you assholes.")
    @commands.command()
    async def edate(self, ctx):
        await ctx.message.delete()
        await ctx.channel.send("can we honestly e date? you're so beautiful. You always make me laugh, you always make me smile. You literally make me want to become a better person... I really enjoy every moment we spend together. My time has no value unless its spent with you. I tell everyone of my irls how awesome you are. Thank you for being you. Whenever you need someone to be there for you, know that i’ll always be right there by your side. I love you so much. I don’t think you ever realize how amazing you are sometimes. Life isn’t as fun when you’re not around. You are truly stunning. I want you to be my soulmate. I love the way you smile, your eyes are absolutely gorgeous. If I had a star for everytime you crossed my mind i could make the entire galaxy. Your personality is as pretty as you are and thats saying something. I love you, please date me. I am not even calling it e dating anymore because I know we will meet soon enough heart OK I ADMIT IT I LOVE YOU OK i hecking love you and it breaks my heart when i see you play with someone else or anyone commenting in your profile i just want to be your girlfriend and put a heart in my profile linking to your profile and have a walltext of you commenting cute things i want to play video games talk in discord all night and watch a movie together but you just seem so uninsterested in me it hecking kills me and i cant take it anymore i want to remove you but i care too much about you so please i’m begging you to eaither love me back or remove me and never contact me again it hurts so much to say this because i need you by my side but if you dont love me then i want you to leave because seeing your icon in my friendlist would kill me everyday of my pathetic life.")
    @commands.command()
    async def notgonnabeactive(self, ctx):
        await ctx.message.delete()
        await ctx.channel.send("Not gonna be active on Discord tonight. I'm meeting a girl (a real one) in half an hour (wouldn't expect a lot of you to understand anyway) so please don't DM me asking me where I am (im with the girl, ok) you'll most likely get aired because i'll be with the girl (again I don't expect you to understand) shes actually really interested in me and its not a situation i can pass up for some meaningless Discord degenerates (because i'll be meeting a girl, not that you really are going to understand) this is my life now. Meeting women and not wasting my precious time online, I have to move on from such simple things and branch out (you wouldnt understand)\n\nNot gonna be active on Discord tonight. I'm taking a shower (a real one) in half an hour (wouldn't expect a lot of you to understand anyway) so pleas don't DM me asking me where I am (im taking a shower, ok) you'll most likely get aired because ill be in the shower (again I don't expect you to understand) I'm actually really smelly and its not a situation I can pass up for some meaningless Discord degenerates (because ill be taking a shower, not that you really are going to understand) this is my life now. Taking showers and not wasting my precious time online, I have to move on from such simple things and branch out (you wouldn't undertsand).")
    @commands.command()
    async def bubblewrap(self, ctx):
        await ctx.message.delete()
        await ctx.channel.send("Bubble wrap be like : \n\n||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop|| ||pop||")
    @commands.command()
    async def yourmotherandi(self, ctx):
        await ctx.message.delete()
        await ctx.channel.send("Your mother and I had very loud, long, and passionate sexual intercourse last night. It was so loud, your neighbors called the police to report a noise complaint, the police thought your mother was in danger from how ear piercing her moans were, and ended up breaking down the door to find me shafting my 10.7 inch rock hard penis in and out of her tight vagina. They were so impressed they stayed to watch. I was shanking it, I was cranking it, and finally, I ejaculated so much it splattered throughout your entire house. I performed so well that your mother, the police, and your neighbors tipped me for it.")
    @commands.command()
    async def senpai(self, ctx):
        await ctx.message.delete()
        await ctx.channel.send("Hey senpai... uwu\nthrows 3 consecutive punches to your ribcage\nOoh, you like that huh? Pervert! :3\ndelivers several kicks to your jaw\nOops!\nthrows you to the ground\nOwO senpai!\nsits on your face\nPervert!\nrips a fat fucking fart\nOoh, that was a bad boy!\nanother\nUwU you sick pervert!\nstands up\nAm I teasing you? UwU\npicks up an unsharpened knife\nowoo! :3\nuses the knife to scrath your stomach with pure, feral force\nOops! Spilled some blood there didn't you? OwO\ndumps 2 galons of bleach on you\nuwuuuuu :3\nbrazillian jiu-jitsu sequence\nPervert!\nbreaks your forearm\noops!\nqueefs\n:3")
    @commands.command()
    async def discordmodgoodbye(self, ctx):
        await ctx.message.delete()
        await ctx.channel.send("Whatever, this is my last message to you ever so remember this, I thought you were such a great person which is why I admired you and wished I could be like you but of course you became like this, I never claim to be innocent and I still don't but I know from what I can see that you are not a good person anymore, I got you a full price game because I cared a lot about you and so you didn't have to worry about the whole thing with your dad, I always had your back whenever you had problems, I trusted you with my secrets, I got you into anime, when you said you were leaving Discord that one time I jumped to try to help you I felt really close to you and then you just one day decide 'Hey I'm not your friend anymore and I don't like you' without even an indication, you became a person that decided to play with my emotions, you took advantage of my trust that time when the confession bot was being used and then it turned out to be you and you allowed me to accuse people which made me look bad yet I still forgave you and let myself believe that you had a single ounce of care for me, sure I may be far from a good person but I at least am a loyal fried that would go many lengths to protect that friendship no matter what, but even after you said I was manipulative (which btw effected me to the point where I'm afraid to talk about my feelings to anyone) I still decided to believe you because I cared and thought you knew best but while talking to real friends that care about me for real I realize that you were wrong. You used to say to be so mature but now you act childish, you also seem ungrateful but with that being said I still know you're a trustworthy person kinda also me and the others have really liked the peaceful server ever since you guys with your spamming and wanting to say the N word left(And then a few weeks later he decided to message him exactly at 12 am on his birthday)12:00 am November 6 aka your birthday, I memorized when your birthday was because before all this stuff happened I was planning something for your birthday but I guess that can't happen now, and no Birthday bot is gone so that didn't remind me, I may not be the person you want to hear this from but Happy Birthday dude, I hope this year is full of enjoyment and happiness for you, you deserve it 👍this is the least I can do")

def setup(bot):
    bot.add_cog(Copypastas(bot))